default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  host: db  # Matches the service name in docker-compose.yml
  port: 5432
  pool: 5

development:
  <<: *default
  database: quote_voting_app_development

test:
  <<: *default
  database: quote_voting_app_test

production:
  <<: *default
  database: quote_voting_app_production
